/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsVersionsRouteImport } from './routes/settings/versions'
import { Route as SettingsModsRouteImport } from './routes/settings/mods'
import { Route as SettingsEngineRouteImport } from './routes/settings/engine'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsVersionsRoute = SettingsVersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsModsRoute = SettingsModsRouteImport.update({
  id: '/mods',
  path: '/mods',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsEngineRoute = SettingsEngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/marketplace': typeof MarketplaceRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/engine': typeof SettingsEngineRoute
  '/settings/mods': typeof SettingsModsRoute
  '/settings/versions': typeof SettingsVersionsRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/marketplace': typeof MarketplaceRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/engine': typeof SettingsEngineRoute
  '/settings/mods': typeof SettingsModsRoute
  '/settings/versions': typeof SettingsVersionsRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/marketplace': typeof MarketplaceRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/engine': typeof SettingsEngineRoute
  '/settings/mods': typeof SettingsModsRoute
  '/settings/versions': typeof SettingsVersionsRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/marketplace'
    | '/settings'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/engine'
    | '/settings/mods'
    | '/settings/versions'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/marketplace'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/engine'
    | '/settings/mods'
    | '/settings/versions'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/marketplace'
    | '/settings'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/engine'
    | '/settings/mods'
    | '/settings/versions'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketplaceRoute: typeof MarketplaceRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/versions': {
      id: '/settings/versions'
      path: '/versions'
      fullPath: '/settings/versions'
      preLoaderRoute: typeof SettingsVersionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/mods': {
      id: '/settings/mods'
      path: '/mods'
      fullPath: '/settings/mods'
      preLoaderRoute: typeof SettingsModsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/engine': {
      id: '/settings/engine'
      path: '/engine'
      fullPath: '/settings/engine'
      preLoaderRoute: typeof SettingsEngineRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsEngineRoute: typeof SettingsEngineRoute
  SettingsModsRoute: typeof SettingsModsRoute
  SettingsVersionsRoute: typeof SettingsVersionsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsEngineRoute: SettingsEngineRoute,
  SettingsModsRoute: SettingsModsRoute,
  SettingsVersionsRoute: SettingsVersionsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketplaceRoute: MarketplaceRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
